name: CD

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

env:
#  AWS_ACCESS_KEY_ID: ${{ secrets.DOMAIN_PUBLISHER_AWS_ACCESS_KEY_ID }}
#  AWS_SECRET_ACCESS_KEY: ${{ secrets.DOMAIN_PUBLISHER_AWS_ACCESS_KEY_SECRET }}
  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
  AWS_CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
  AWS_DEFAULT_REGION: 'us-east-1'
  SOURCE_DIR: '.'
  DEST_DIR: '/'

jobs:
  cd:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: CD
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.DOMAIN_PUBLISHER_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DOMAIN_PUBLISHER_AWS_ACCESS_KEY_SECRET }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Sync files to S3
        run: |
          aws s3 sync ${{ env.SOURCE_DIR }} s3://${{ env.AWS_S3_BUCKET }}${{ env.DEST_DIR }} --delete --exclude '.*git*'

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.AWS_CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"

#      - name: Sync to S3
#        uses: ItsKarma/aws-cli@v1.70.0
#        with:
#          args: s3 sync --delete ${{env.SOURCE_DIR}} s3://${{env.AWS_S3_BUCKET}}${{env.DEST_DIR}}
#      - name: Invalidate Cloudfront
#        uses: ItsKarma/aws-cli@v1.70.0
#        with:
#          args: aws cloudfront create-invalidation \
#            --distribution-id ${{ env.AWS_CLOUDFRONT_DISTRIBUTION_ID }} \
#            --paths "/*"
